### PR TITLE
Updated Kaia changes

### PR DESCRIPTION
**Pull request by praveen-kaia**
## Proposed changes

- Updated Kaia related changes

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or Enhancement
- [X] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [X] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the CLA by posting "I have read the CLA Document and I hereby sign the CLA" in the comment
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by praveen-kaia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ian0371 — APPROVED** [review]
Do we use the version 1.0.6 for the first release?

**Comment by praveen-kaia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by blukat29** [comment]
<s>@ian0371 I think so? At least some `@kaiachain/` npm packages are inheriting the last version from `@klaytn` (e.g. https://www.npmjs.com/package/@klaytn/kss-dexs -> https://www.npmjs.com/package/@kaiachain/kss-dexs)</s>
Oh we're rebooting from 1.0.0. Sorry.

**Comment by Sotatek-TinnNguyen** [comment]
recheck

**Pull request merged**
